name: Full Deploy to All-Inkl

on:
  workflow_dispatch:  # Nur manuell auslösen

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql, json, curl
    
    - name: Run tests
      run: |
        # Führe PHP Syntax Checks aus
        find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
    
    - name: Deploy via lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        lftp -c "
          set ftp:ssl-allow no
          set ftp:passive-mode yes
          set net:timeout 10
          set net:max-retries 3
          set net:reconnect-interval-base 5
          open ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}@w019e3c7.kasserver.com
          mirror -R --delete --verbose --overwrite \
            --exclude .git/ \
            --exclude .github/ \
            --exclude .env \
            --exclude .env.example \
            --exclude README.md \
            --exclude INSTALLATION.md \
            --exclude debug.php \
            --exclude node_modules/ \
            ./ /www/htdocs/w019e3c7/firmenpro.de/
          bye
        "
    
    - name: Clear cache (optional)
      continue-on-error: true
      run: |
        # Webhook zum Cache leeren (falls eingerichtet)
        curl -X POST https://firmenpro.de/api/cache/clear \
          -H "X-Deploy-Token: ${{ secrets.DEPLOY_TOKEN }}" \
          || echo "Cache clear skipped"