name: Quick Deploy (Changed Files Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-changed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Needed to get previous commit
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Get changed files
      id: changed-files
      run: |
        echo "Changed files:"
        git diff --name-only HEAD^ HEAD || git diff --name-only $(git rev-list --max-parents=0 HEAD) HEAD
        echo "files=$(git diff --name-only HEAD^ HEAD 2>/dev/null || git diff --name-only $(git rev-list --max-parents=0 HEAD) HEAD)" >> $GITHUB_OUTPUT
    
    - name: Test FTP Connection
      run: |
        echo "Testing FTP connection..."
        # Simple upload test first
        curl -T ftp-test-simple.txt \
          ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}@w019e3c7.kasserver.com/www/htdocs/w019e3c7/firmenpro.de/ftp-test-simple.txt \
          -v || echo "Upload failed"
    
    - name: Deploy changed files only
      run: |
        echo "=== STARTING DEPLOYMENT ==="
        
        # Get changed files
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD 2>/dev/null || git diff --name-only $(git rev-list --max-parents=0 HEAD) HEAD)
        
        if [ -z "$CHANGED_FILES" ]; then
          echo "No files changed"
          exit 0
        fi
        
        echo "Changed files detected:"
        echo "$CHANGED_FILES"
        echo "---"
        
        # Deploy each changed file
        for file in $CHANGED_FILES; do
          echo "Processing: $file"
          
          # Skip files we don't want to deploy
          if [[ "$file" == .github/* ]] || [[ "$file" == ".env" ]] || [[ "$file" == "README.md" ]] || [[ "$file" == ".gitignore" ]]; then
            echo "  → Skipping (excluded)"
            continue
          fi
          
          # Check if file exists
          if [ ! -f "$file" ]; then
            echo "  → File deleted, skipping"
            continue
          fi
          
          echo "  → Uploading to server..."
          
          # Method 1: Try with curl first
          echo "  → Trying curl upload..."
          if curl -T "$file" \
               ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}@w019e3c7.kasserver.com/www/htdocs/w019e3c7/firmenpro.de/$file \
               --create-dirs \
               -v; then
            echo "  ✓ Upload successful with curl!"
          else
            echo "  ✗ Curl failed, trying lftp..."
            
            # Method 2: Fallback to lftp
            sudo apt-get install -y lftp >/dev/null 2>&1
            
            DIR=$(dirname "$file")
            if lftp -c "
              set ftp:ssl-allow no
              set ftp:passive-mode yes
              set net:timeout 30
              open ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}@w019e3c7.kasserver.com
              mkdir -pf /www/htdocs/w019e3c7/firmenpro.de/$DIR
              put -O /www/htdocs/w019e3c7/firmenpro.de/$DIR $file
              bye
            "; then
              echo "  ✓ Upload successful with lftp!"
            else
              echo "  ✗ Both upload methods failed for $file"
            fi
          fi
          
          echo "---"
        done
        
        echo "=== DEPLOYMENT COMPLETE ====="