name: Simple Deploy Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Simple FTP Upload
      run: |
        echo "=== SIMPLE FTP DEPLOYMENT ==="
        echo "Uploading test.php..."
        
        # Create .netrc file for authentication
        cat > ~/.netrc << EOF
        machine w019e3c7.kasserver.com
        login ${{ secrets.FTP_USER }}
        password ${{ secrets.FTP_PASS }}
        EOF
        
        chmod 600 ~/.netrc
        
        # Upload using standard ftp command
        ftp -n -v w019e3c7.kasserver.com << EOF
        cd /www/htdocs/w019e3c7/firmenpro.de
        put test.php
        put deployment-test.txt
        ls -la
        quit
        EOF
        
        echo "=== DONE ==="