name: SSH Deploy to All-Inkl

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy via SSH
      run: |
        # Install sshpass
        sudo apt-get update && sudo apt-get install -y sshpass rsync
        
        # Deploy files via rsync over SSH
        echo "Deploying files to All-Inkl..."
        sshpass -p "${{ secrets.SSH_PASS }}" rsync -avz --delete \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='.env' \
          --exclude='node_modules/' \
          --exclude='debug.php' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ssh-w019e3c7@w019e3c7.kasserver.com:/www/htdocs/w019e3c7/firmenpro.de/
        
        echo "Deployment complete!"
          
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no \
          ssh-w019e3c7@w019e3c7.kasserver.com \
          "cd /www/htdocs/w019e3c7/firmenpro.de/ && head -5 test.php | grep -E '(DOCTYPE|Updated)' && echo 'Deployment successful!' || echo 'Deployment may have failed'"